dataset_name: 2JOF
names: [2JOF]
tag: ""
save_dir: /mnt/lustre/hsm/nlsas/notape/home/usc/qo/supepmem/DANIEL/75_per_leaflet/simulacion_openmm/NVT_TODAS/test_def_MASIVA_ARCO
stride: 30        #tenia 5, #config tmb guay 1
batch_size: 100
device: cpu
save_figs: true
embedding_map: cg_mapping #input_generator.CGEmbeddingMapFiveBead

